/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.CardLayout;
import java.util.Collections;
import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author JeffChoi
 */
public class BonusQuizUI2 extends javax.swing.JFrame {
    private Game game;
    private CardLayout card;
    
    /**
     * Creates new form BonusQuizUI2
     */
    public BonusQuizUI2(Game game) {
        this.setVisible(true);
        this.game = game;
        initComponents();
        
        card = (CardLayout) quizPanel.getLayout();
        card.show(quizPanel, "cardStart");
        buttonNext.setText("Start");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupForQuiz1 = new javax.swing.ButtonGroup();
        groupForQuiz2 = new javax.swing.ButtonGroup();
        groupForQuiz3 = new javax.swing.ButtonGroup();
        groupForQuiz4 = new javax.swing.ButtonGroup();
        groupForQuiz5 = new javax.swing.ButtonGroup();
        groupForQuiz6 = new javax.swing.ButtonGroup();
        groupForQuiz7 = new javax.swing.ButtonGroup();
        groupForQuiz8 = new javax.swing.ButtonGroup();
        groupForQuiz9 = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        quizPanel = new javax.swing.JPanel();
        startPage = new javax.swing.JPanel();
        quiz1 = new javax.swing.JPanel();
        quizOneLabel = new javax.swing.JLabel();
        answer1A = new javax.swing.JRadioButton();
        answer1B = new javax.swing.JRadioButton();
        answer1C = new javax.swing.JRadioButton();
        answer1D = new javax.swing.JRadioButton();
        quiz2 = new javax.swing.JPanel();
        quizTwoLabel = new javax.swing.JLabel();
        answer2A = new javax.swing.JRadioButton();
        answer2B = new javax.swing.JRadioButton();
        answer2C = new javax.swing.JRadioButton();
        answer2D = new javax.swing.JRadioButton();
        quiz3 = new javax.swing.JPanel();
        quizThreeLabel = new javax.swing.JLabel();
        answer3A = new javax.swing.JRadioButton();
        answer3B = new javax.swing.JRadioButton();
        answer3C = new javax.swing.JRadioButton();
        answer3D = new javax.swing.JRadioButton();
        quiz4 = new javax.swing.JPanel();
        quizFourLabel = new javax.swing.JLabel();
        answer4A = new javax.swing.JRadioButton();
        answer4B = new javax.swing.JRadioButton();
        answer4C = new javax.swing.JRadioButton();
        answer4D = new javax.swing.JRadioButton();
        quiz5 = new javax.swing.JPanel();
        quizFiveLabel = new javax.swing.JLabel();
        answer5A = new javax.swing.JRadioButton();
        answer5B = new javax.swing.JRadioButton();
        answer5C = new javax.swing.JRadioButton();
        answer5D = new javax.swing.JRadioButton();
        quiz6 = new javax.swing.JPanel();
        quizSixLabel = new javax.swing.JLabel();
        answer6A = new javax.swing.JRadioButton();
        answer6B = new javax.swing.JRadioButton();
        answer6C = new javax.swing.JRadioButton();
        answer6D = new javax.swing.JRadioButton();
        endPage = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        buttonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Gulim", 3, 24)); // NOI18N
        welcomeLabel.setText("Welcome to Bonus Quiz!");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(welcomeLabel)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(welcomeLabel)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        quizPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout startPageLayout = new javax.swing.GroupLayout(startPage);
        startPage.setLayout(startPageLayout);
        startPageLayout.setHorizontalGroup(
            startPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        startPageLayout.setVerticalGroup(
            startPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        quizPanel.add(startPage, "cardStart");

        quizOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizOneLabel.setText("Q. Approximately how many kiwis are left in New Zealand?");

        groupForQuiz1.add(answer1A);
        answer1A.setText("54,000");

        groupForQuiz1.add(answer1B);
        answer1B.setText("99,000");

        groupForQuiz1.add(answer1C);
        answer1C.setText("68,000");

        groupForQuiz1.add(answer1D);
        answer1D.setText("120,000");

        javax.swing.GroupLayout quiz1Layout = new javax.swing.GroupLayout(quiz1);
        quiz1.setLayout(quiz1Layout);
        quiz1Layout.setHorizontalGroup(
            quiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(quizOneLabel)
                .addGap(107, 107, 107))
            .addGroup(quiz1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer1D)
                    .addComponent(answer1C)
                    .addComponent(answer1B)
                    .addComponent(answer1A))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quiz1Layout.setVerticalGroup(
            quiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizOneLabel)
                .addGap(18, 18, 18)
                .addComponent(answer1A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1D)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        quizPanel.add(quiz1, "card1");

        quizTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizTwoLabel.setText("Q. On average, how many kiwis is New Zealand losing per week?");

        groupForQuiz2.add(answer2A);
        answer2A.setText("20");
        answer2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2AActionPerformed(evt);
            }
        });

        groupForQuiz2.add(answer2B);
        answer2B.setText("40");

        groupForQuiz2.add(answer2C);
        answer2C.setText("5");

        groupForQuiz2.add(answer2D);
        answer2D.setText("10");

        javax.swing.GroupLayout quiz2Layout = new javax.swing.GroupLayout(quiz2);
        quiz2.setLayout(quiz2Layout);
        quiz2Layout.setHorizontalGroup(
            quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz2Layout.createSequentialGroup()
                .addGroup(quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quiz2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer2D)
                            .addComponent(answer2C)
                            .addComponent(answer2B)
                            .addComponent(answer2A)))
                    .addGroup(quiz2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(quizTwoLabel)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        quiz2Layout.setVerticalGroup(
            quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizTwoLabel)
                .addGap(18, 18, 18)
                .addComponent(answer2A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer2C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer2D)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        quizPanel.add(quiz2, "card2");

        quizThreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizThreeLabel.setText("Q. What time of day are kiwi's most active?");

        groupForQuiz3.add(answer3A);
        answer3A.setText("Day");

        groupForQuiz3.add(answer3B);
        answer3B.setText("Night");

        groupForQuiz3.add(answer3C);
        answer3C.setText("Both");

        groupForQuiz3.add(answer3D);
        answer3D.setText("Neither");

        javax.swing.GroupLayout quiz3Layout = new javax.swing.GroupLayout(quiz3);
        quiz3.setLayout(quiz3Layout);
        quiz3Layout.setHorizontalGroup(
            quiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer3D)
                    .addComponent(answer3C)
                    .addComponent(answer3B)
                    .addComponent(answer3A))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizThreeLabel)
                .addGap(154, 154, 154))
        );
        quiz3Layout.setVerticalGroup(
            quiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizThreeLabel)
                .addGap(18, 18, 18)
                .addComponent(answer3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer3C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer3D)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        quizPanel.add(quiz3, "card3");

        quizFourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizFourLabel.setText("Q. In which of these places do kiwi's not like to rest?");

        groupForQuiz4.add(answer4A);
        answer4A.setText("Burrows");

        groupForQuiz4.add(answer4B);
        answer4B.setText("Riverbed");

        groupForQuiz4.add(answer4C);
        answer4C.setText("Hollow logs");

        groupForQuiz4.add(answer4D);
        answer4D.setText("Under dense vegetation");

        javax.swing.GroupLayout quiz4Layout = new javax.swing.GroupLayout(quiz4);
        quiz4.setLayout(quiz4Layout);
        quiz4Layout.setHorizontalGroup(
            quiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz4Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer4D)
                    .addComponent(answer4C)
                    .addComponent(answer4B)
                    .addComponent(answer4A))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizFourLabel)
                .addGap(154, 154, 154))
        );
        quiz4Layout.setVerticalGroup(
            quiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizFourLabel)
                .addGap(18, 18, 18)
                .addComponent(answer4A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer4B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer4C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer4D)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        quizPanel.add(quiz4, "card4");

        quizFiveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizFiveLabel.setText("Q. Where are a kiwi's nostrils located?");

        groupForQuiz5.add(answer5A);
        answer5A.setText("On their feet");

        groupForQuiz5.add(answer5B);
        answer5B.setText("Under their eyes");

        groupForQuiz5.add(answer5C);
        answer5C.setText("Behind the head");

        groupForQuiz5.add(answer5D);
        answer5D.setText("End of their long bill");

        javax.swing.GroupLayout quiz5Layout = new javax.swing.GroupLayout(quiz5);
        quiz5.setLayout(quiz5Layout);
        quiz5Layout.setHorizontalGroup(
            quiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz5Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer5D)
                    .addComponent(answer5C)
                    .addComponent(answer5B)
                    .addComponent(answer5A))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizFiveLabel)
                .addGap(154, 154, 154))
        );
        quiz5Layout.setVerticalGroup(
            quiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizFiveLabel)
                .addGap(18, 18, 18)
                .addComponent(answer5A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer5B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer5C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer5D)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        quizPanel.add(quiz5, "card4");

        quizSixLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizSixLabel.setText("Q. The kiwi egg averages what percentage of the female's body weight?");

        groupForQuiz6.add(answer6A);
        answer6A.setText("15%");

        groupForQuiz6.add(answer6B);
        answer6B.setText("25%");

        groupForQuiz6.add(answer6C);
        answer6C.setText("5%");

        groupForQuiz6.add(answer6D);
        answer6D.setText("10%");

        javax.swing.GroupLayout quiz6Layout = new javax.swing.GroupLayout(quiz6);
        quiz6.setLayout(quiz6Layout);
        quiz6Layout.setHorizontalGroup(
            quiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz6Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer6D)
                    .addComponent(answer6C)
                    .addComponent(answer6B)
                    .addComponent(answer6A))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizSixLabel)
                .addGap(67, 67, 67))
        );
        quiz6Layout.setVerticalGroup(
            quiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizSixLabel)
                .addGap(18, 18, 18)
                .addComponent(answer6A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer6B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer6C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer6D)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        quizPanel.add(quiz6, "card4");

        endLabel.setFont(new java.awt.Font("Gulim", 3, 24)); // NOI18N
        endLabel.setText("Thanks for playing this game");

        scoreLabel.setText("Your score is.... ");

        javax.swing.GroupLayout endPageLayout = new javax.swing.GroupLayout(endPage);
        endPage.setLayout(endPageLayout);
        endPageLayout.setHorizontalGroup(
            endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPageLayout.createSequentialGroup()
                .addGroup(endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endPageLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(endLabel))
                    .addGroup(endPageLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(scoreLabel)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        endPageLayout.setVerticalGroup(
            endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endLabel)
                .addGap(43, 43, 43)
                .addComponent(scoreLabel)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        quizPanel.add(endPage, "cardEnd");

        getContentPane().add(quizPanel, java.awt.BorderLayout.CENTER);

        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(buttonNext)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(buttonNext)
                .addContainerGap())
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        buttonNext.setEnabled(false);
        Collections.shuffle(game.getFacts());
        
        
        //CardLayout card = (CardLayout) quizPanel.getLayout();
        //card.next(quizPanel);
        if (iterator < 5) {
            // show card
            if (game.getFacts().get(iterator).equals("There are about 68,000 kiwi left in all of New Zealand.")) {
                //card.show(quizPanel, "card1");
                if (answer1C.isSelected()){
                    //JOptionPane.showMessageDialog(this, endPage, title, HEIGHT, icon);
                }
                // game.addPointS(3)
                // show dialog "Correct"
                 buttonNext.setEnabled(true);
                 card.show(quizPanel, "card1");
            } else if (game.getFacts().get(iterator).equals("We are losing 2% of our unmanaged kiwi every year –that's around 20 per week.")) {
                card.show(quizPanel, "card2");
            } else if (game.getFacts().get(iterator).equals("Kiwi are mostly nocturnal.")) {
                card.show(quizPanel, "card3");
            } else if (game.getFacts().get(iterator).equals("Kiwi nest in burrows, hollow logs or under dense vegetation.")) {
                card.show(quizPanel, "card4");
            } else if (game.getFacts().get(iterator).equals("Kiwi are the only bird to have nostrils at the end of their very long bill. Their nostrils are used to probe in the ground, sniffing out invertebrates to eat, along with some fallen fruit.")) {
                card.show(quizPanel, "card5");
            } else if (game.getFacts().get(iterator).equals("The egg averages 15% of the female's body weight (compared to 2% for the ostrich).")) {
                card.show(quizPanel, "card6");
            } else if (game.getFacts().get(iterator).equals("Females are larger than males (up to 3.3 kg and 45 cm).")) {
                card.show(quizPanel, "card7");
            } else if (game.getFacts().get(iterator).equals("Kiwi are long-lived, and depending on the species live for between 25 and 50 years.")) {
                card.show(quizPanel, "card8");
            } else if (game.getFacts().get(iterator).equals("Rat")) {
                card.show(quizPanel, "card9");
            } else if (game.getFacts().get(iterator).equals("Cat")) {
                card.show(quizPanel, "card10");
            } else if (game.getFacts().get(iterator).equals("Kiore")) {
                card.show(quizPanel, "card11");
            } else if (game.getFacts().get(iterator).equals("Stoat")) {
                card.show(quizPanel, "card12");
            } else if (game.getFacts().get(iterator).equals("Possum")) {
                card.show(quizPanel, "card13");
            } else if (game.getFacts().get(iterator).equals("Bat")) {
                card.show(quizPanel, "card14");
            } else if (game.getFacts().get(iterator).equals("Weta")) {
                card.show(quizPanel, "card15");
            } else if (game.getFacts().get(iterator).equals("Tuatara")) {
                card.show(quizPanel, "card16");
            } else if (game.getFacts().get(iterator).equals("Kakapu")) {
                card.show(quizPanel, "card17");
            }
            //}
            //else if{
            //
            //}
            //card.show(quizPanel, "card"+iterator);
            iterator++;
        }else if(iterator < 5){
            
        }
        else{
            // show endCard
            card.show(quizPanel, "cardEnd");
            //scoreLabel.setText("Your score is "+game.getScore());
            // set text to show score
            // game.ifhighScore(game.getScore);
            // popup to Save score?
            // game.addHighScore(game.getScore, jTextField.getText().toString);
            
        }
        
    }//GEN-LAST:event_buttonNextActionPerformed

    private void answer2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2AActionPerformed

    public void createQuiz(){
        //Collections.shuffle(game.getFacts());
        /*
        for(int i = 0; i < 5; i++){
            if(i == 0){
                if(facts.get(i).equals("There are about 68,000 kiwi left in all of New Zealand.")){
                    /
                }else if(facts.get(i).equals("We are losing 2% of our unmanaged kiwi every year –that's around 20 per week.")){
                    
                }else if(facts.get(i).equals("Kiwi are mostly nocturnal.")){
                    
                }else if(facts.get(i).equals("Kiwi nest in burrows, hollow logs or under dense vegetation.")){
                    
                }else if(facts.get(i).equals("Kiwi are the only bird to have nostrils at the end of their very long bill. Their nostrils are used to probe in the ground, sniffing out invertebrates to eat, along with some fallen fruit.")){
                    
                }else if(facts.get(i).equals("The egg averages 15% of the female's body weight (compared to 2% for the ostrich).")){
                    
                }else if(facts.get(i).equals("Females are larger than males (up to 3.3 kg and 45 cm).")){
                    
                }else if(facts.get(i).equals("Kiwi are long-lived, and depending on the species live for between 25 and 50 years.")){
                    
                }else if(facts.get(i).equals("Rat")){
                    
                }else if(facts.get(i).equals("Cat")){
                    
                }else if(facts.get(i).equals("Kiore")){
                    
                }else if(facts.get(i).equals("Stoat")){
                    
                }else if(facts.get(i).equals("Possum")){
                    
                }else if(facts.get(i).equals("Bat")){
                    
                }else if(facts.get(i).equals("Weta")){
                    
                }else if(facts.get(i).equals("Tuatara")){
                    
                }else if(facts.get(i).equals("Kakapu")){
                    
                }
            }else if(i == 1){
                
            }else if(i == 2){
                
            }else if(i == 3){
                
            }else{
                
            }
            
        }
        */
    }
    
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BonusQuizUI2().setVisible(true);
//            }
//        });
//    }
    private int iterator = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answer1A;
    private javax.swing.JRadioButton answer1B;
    private javax.swing.JRadioButton answer1C;
    private javax.swing.JRadioButton answer1D;
    private javax.swing.JRadioButton answer2A;
    private javax.swing.JRadioButton answer2B;
    private javax.swing.JRadioButton answer2C;
    private javax.swing.JRadioButton answer2D;
    private javax.swing.JRadioButton answer3A;
    private javax.swing.JRadioButton answer3B;
    private javax.swing.JRadioButton answer3C;
    private javax.swing.JRadioButton answer3D;
    private javax.swing.JRadioButton answer4A;
    private javax.swing.JRadioButton answer4B;
    private javax.swing.JRadioButton answer4C;
    private javax.swing.JRadioButton answer4D;
    private javax.swing.JRadioButton answer5A;
    private javax.swing.JRadioButton answer5B;
    private javax.swing.JRadioButton answer5C;
    private javax.swing.JRadioButton answer5D;
    private javax.swing.JRadioButton answer6A;
    private javax.swing.JRadioButton answer6B;
    private javax.swing.JRadioButton answer6C;
    private javax.swing.JRadioButton answer6D;
    private javax.swing.JButton buttonNext;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel endPage;
    private javax.swing.ButtonGroup groupForQuiz1;
    private javax.swing.ButtonGroup groupForQuiz2;
    private javax.swing.ButtonGroup groupForQuiz3;
    private javax.swing.ButtonGroup groupForQuiz4;
    private javax.swing.ButtonGroup groupForQuiz5;
    private javax.swing.ButtonGroup groupForQuiz6;
    private javax.swing.ButtonGroup groupForQuiz7;
    private javax.swing.ButtonGroup groupForQuiz8;
    private javax.swing.ButtonGroup groupForQuiz9;
    private javax.swing.JPanel quiz1;
    private javax.swing.JPanel quiz2;
    private javax.swing.JPanel quiz3;
    private javax.swing.JPanel quiz4;
    private javax.swing.JPanel quiz5;
    private javax.swing.JPanel quiz6;
    private javax.swing.JLabel quizFiveLabel;
    private javax.swing.JLabel quizFourLabel;
    private javax.swing.JLabel quizOneLabel;
    private javax.swing.JPanel quizPanel;
    private javax.swing.JLabel quizSixLabel;
    private javax.swing.JLabel quizThreeLabel;
    private javax.swing.JLabel quizTwoLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel startPage;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
