/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.CardLayout;
import java.util.Collections;
import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author JeffChoi
 */
public class BonusQuizUI2 extends javax.swing.JFrame {
    private Game game;
    private CardLayout card;
    
    /**
     * Creates new form BonusQuizUI2
     */
    public BonusQuizUI2(Game game) {
        this.setVisible(true);
        this.game = game;
        initComponents();
        
        card = (CardLayout) quizPanel.getLayout();
        card.show(quizPanel, "cardStart");
        buttonNext.setText("Start");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupForQuiz1 = new javax.swing.ButtonGroup();
        groupForQuiz2 = new javax.swing.ButtonGroup();
        groupForQuiz3 = new javax.swing.ButtonGroup();
        groupForQuiz4 = new javax.swing.ButtonGroup();
        groupForQuiz5 = new javax.swing.ButtonGroup();
        groupForQuiz6 = new javax.swing.ButtonGroup();
        groupForQuiz7 = new javax.swing.ButtonGroup();
        groupForQuiz8 = new javax.swing.ButtonGroup();
        groupForQuiz9 = new javax.swing.ButtonGroup();
        groupForQuiz17 = new javax.swing.ButtonGroup();
        groupForQuiz16 = new javax.swing.ButtonGroup();
        groupForQuiz15 = new javax.swing.ButtonGroup();
        groupForQuiz14 = new javax.swing.ButtonGroup();
        groupForQuiz13 = new javax.swing.ButtonGroup();
        groupForQuiz12 = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        quizPanel = new javax.swing.JPanel();
        startPage = new javax.swing.JPanel();
        quiz1 = new javax.swing.JPanel();
        quizOneLabel = new javax.swing.JLabel();
        answer1A = new javax.swing.JRadioButton();
        answer1B = new javax.swing.JRadioButton();
        answer1C = new javax.swing.JRadioButton();
        answer1D = new javax.swing.JRadioButton();
        quiz2 = new javax.swing.JPanel();
        quizTwoLabel = new javax.swing.JLabel();
        answer2A = new javax.swing.JRadioButton();
        answer2B = new javax.swing.JRadioButton();
        answer2C = new javax.swing.JRadioButton();
        answer2D = new javax.swing.JRadioButton();
        quiz3 = new javax.swing.JPanel();
        quizThreeLabel = new javax.swing.JLabel();
        answer3A = new javax.swing.JRadioButton();
        answer3B = new javax.swing.JRadioButton();
        answer3C = new javax.swing.JRadioButton();
        answer3D = new javax.swing.JRadioButton();
        quiz4 = new javax.swing.JPanel();
        quizFourLabel = new javax.swing.JLabel();
        answer4A = new javax.swing.JRadioButton();
        answer4B = new javax.swing.JRadioButton();
        answer4C = new javax.swing.JRadioButton();
        answer4D = new javax.swing.JRadioButton();
        quiz5 = new javax.swing.JPanel();
        quizFiveLabel = new javax.swing.JLabel();
        answer5A = new javax.swing.JRadioButton();
        answer5B = new javax.swing.JRadioButton();
        answer5C = new javax.swing.JRadioButton();
        answer5D = new javax.swing.JRadioButton();
        quiz6 = new javax.swing.JPanel();
        quizSixLabel = new javax.swing.JLabel();
        answer6A = new javax.swing.JRadioButton();
        answer6B = new javax.swing.JRadioButton();
        answer6C = new javax.swing.JRadioButton();
        answer6D = new javax.swing.JRadioButton();
        endPage = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        quiz17 = new javax.swing.JPanel();
        quizSevenTeenLabel = new javax.swing.JLabel();
        answer17A = new javax.swing.JRadioButton();
        answer17B = new javax.swing.JRadioButton();
        answer17C = new javax.swing.JRadioButton();
        answer17D = new javax.swing.JRadioButton();
        quiz16 = new javax.swing.JPanel();
        quizSixteenLabel = new javax.swing.JLabel();
        answer16A = new javax.swing.JRadioButton();
        answer16B = new javax.swing.JRadioButton();
        answer16C = new javax.swing.JRadioButton();
        answer16D = new javax.swing.JRadioButton();
        quiz15 = new javax.swing.JPanel();
        quizFifteenLabel = new javax.swing.JLabel();
        answer15A = new javax.swing.JRadioButton();
        answer15B = new javax.swing.JRadioButton();
        answer15C = new javax.swing.JRadioButton();
        answer15D = new javax.swing.JRadioButton();
        quiz14 = new javax.swing.JPanel();
        quizForteenLabel = new javax.swing.JLabel();
        answer14A = new javax.swing.JRadioButton();
        answer14B = new javax.swing.JRadioButton();
        answer14C = new javax.swing.JRadioButton();
        answer14D = new javax.swing.JRadioButton();
        quiz13 = new javax.swing.JPanel();
        quizThirteenLabel1 = new javax.swing.JLabel();
        answer13A = new javax.swing.JRadioButton();
        answer13B = new javax.swing.JRadioButton();
        answer13C = new javax.swing.JRadioButton();
        answer13D = new javax.swing.JRadioButton();
        quiz12 = new javax.swing.JPanel();
        quizTwelveLabel2 = new javax.swing.JLabel();
        answer12A = new javax.swing.JRadioButton();
        answer12B = new javax.swing.JRadioButton();
        answer12C = new javax.swing.JRadioButton();
        answer12D = new javax.swing.JRadioButton();
        buttonPanel = new javax.swing.JPanel();
        buttonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Gulim", 3, 24)); // NOI18N
        welcomeLabel.setText("Welcome to Bonus Quiz!");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(welcomeLabel)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(welcomeLabel)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        quizPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout startPageLayout = new javax.swing.GroupLayout(startPage);
        startPage.setLayout(startPageLayout);
        startPageLayout.setHorizontalGroup(
            startPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        startPageLayout.setVerticalGroup(
            startPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        quizPanel.add(startPage, "cardStart");

        quizOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizOneLabel.setText("Q. Approximately how many kiwis are left in New Zealand?");

        groupForQuiz1.add(answer1A);
        answer1A.setText("54,000");

        groupForQuiz1.add(answer1B);
        answer1B.setText("99,000");

        groupForQuiz1.add(answer1C);
        answer1C.setText("68,000");

        groupForQuiz1.add(answer1D);
        answer1D.setText("120,000");

        javax.swing.GroupLayout quiz1Layout = new javax.swing.GroupLayout(quiz1);
        quiz1.setLayout(quiz1Layout);
        quiz1Layout.setHorizontalGroup(
            quiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(quizOneLabel)
                .addGap(107, 107, 107))
            .addGroup(quiz1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer1D)
                    .addComponent(answer1C)
                    .addComponent(answer1B)
                    .addComponent(answer1A))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quiz1Layout.setVerticalGroup(
            quiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizOneLabel)
                .addGap(18, 18, 18)
                .addComponent(answer1A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer1D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz1, "card1");

        quizTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizTwoLabel.setText("Q. On average, how many kiwis is New Zealand losing per week?");

        groupForQuiz2.add(answer2A);
        answer2A.setText("20");
        answer2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2AActionPerformed(evt);
            }
        });

        groupForQuiz2.add(answer2B);
        answer2B.setText("40");

        groupForQuiz2.add(answer2C);
        answer2C.setText("5");

        groupForQuiz2.add(answer2D);
        answer2D.setText("10");

        javax.swing.GroupLayout quiz2Layout = new javax.swing.GroupLayout(quiz2);
        quiz2.setLayout(quiz2Layout);
        quiz2Layout.setHorizontalGroup(
            quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz2Layout.createSequentialGroup()
                .addGroup(quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quiz2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer2D)
                            .addComponent(answer2C)
                            .addComponent(answer2B)
                            .addComponent(answer2A)))
                    .addGroup(quiz2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(quizTwoLabel)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        quiz2Layout.setVerticalGroup(
            quiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizTwoLabel)
                .addGap(18, 18, 18)
                .addComponent(answer2A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer2C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer2D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz2, "card2");

        quizThreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizThreeLabel.setText("Q. What time of day are kiwi's most active?");

        groupForQuiz3.add(answer3A);
        answer3A.setText("Day");

        groupForQuiz3.add(answer3B);
        answer3B.setText("Night");

        groupForQuiz3.add(answer3C);
        answer3C.setText("Both");

        groupForQuiz3.add(answer3D);
        answer3D.setText("Neither");

        javax.swing.GroupLayout quiz3Layout = new javax.swing.GroupLayout(quiz3);
        quiz3.setLayout(quiz3Layout);
        quiz3Layout.setHorizontalGroup(
            quiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer3D)
                    .addComponent(answer3C)
                    .addComponent(answer3B)
                    .addComponent(answer3A))
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizThreeLabel)
                .addGap(154, 154, 154))
        );
        quiz3Layout.setVerticalGroup(
            quiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizThreeLabel)
                .addGap(18, 18, 18)
                .addComponent(answer3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer3C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer3D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz3, "card3");

        quizFourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizFourLabel.setText("Q. In which of these places do kiwi's not like to rest?");

        groupForQuiz4.add(answer4A);
        answer4A.setText("Burrows");

        groupForQuiz4.add(answer4B);
        answer4B.setText("Riverbed");

        groupForQuiz4.add(answer4C);
        answer4C.setText("Hollow logs");

        groupForQuiz4.add(answer4D);
        answer4D.setText("Under dense vegetation");

        javax.swing.GroupLayout quiz4Layout = new javax.swing.GroupLayout(quiz4);
        quiz4.setLayout(quiz4Layout);
        quiz4Layout.setHorizontalGroup(
            quiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz4Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer4D)
                    .addComponent(answer4C)
                    .addComponent(answer4B)
                    .addComponent(answer4A))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizFourLabel)
                .addGap(154, 154, 154))
        );
        quiz4Layout.setVerticalGroup(
            quiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizFourLabel)
                .addGap(18, 18, 18)
                .addComponent(answer4A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer4B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer4C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer4D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz4, "card4");

        quizFiveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizFiveLabel.setText("Q. Where are a kiwi's nostrils located?");

        groupForQuiz5.add(answer5A);
        answer5A.setText("On their feet");

        groupForQuiz5.add(answer5B);
        answer5B.setText("Under their eyes");

        groupForQuiz5.add(answer5C);
        answer5C.setText("Behind the head");

        groupForQuiz5.add(answer5D);
        answer5D.setText("End of their long bill");

        javax.swing.GroupLayout quiz5Layout = new javax.swing.GroupLayout(quiz5);
        quiz5.setLayout(quiz5Layout);
        quiz5Layout.setHorizontalGroup(
            quiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz5Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer5D)
                    .addComponent(answer5C)
                    .addComponent(answer5B)
                    .addComponent(answer5A))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizFiveLabel)
                .addGap(154, 154, 154))
        );
        quiz5Layout.setVerticalGroup(
            quiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizFiveLabel)
                .addGap(18, 18, 18)
                .addComponent(answer5A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer5B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer5C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer5D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz5, "card5");

        quizSixLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizSixLabel.setText("Q. The kiwi egg averages what percentage of the female's body weight?");

        groupForQuiz6.add(answer6A);
        answer6A.setText("15%");

        groupForQuiz6.add(answer6B);
        answer6B.setText("25%");

        groupForQuiz6.add(answer6C);
        answer6C.setText("5%");

        groupForQuiz6.add(answer6D);
        answer6D.setText("10%");

        javax.swing.GroupLayout quiz6Layout = new javax.swing.GroupLayout(quiz6);
        quiz6.setLayout(quiz6Layout);
        quiz6Layout.setHorizontalGroup(
            quiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz6Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer6D)
                    .addComponent(answer6C)
                    .addComponent(answer6B)
                    .addComponent(answer6A))
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizSixLabel)
                .addGap(67, 67, 67))
        );
        quiz6Layout.setVerticalGroup(
            quiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizSixLabel)
                .addGap(18, 18, 18)
                .addComponent(answer6A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer6B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer6C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer6D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz6, "card6");

        endLabel.setFont(new java.awt.Font("Gulim", 3, 24)); // NOI18N
        endLabel.setText("Thanks for playing this game");

        scoreLabel.setText("Your score is.... ");

        javax.swing.GroupLayout endPageLayout = new javax.swing.GroupLayout(endPage);
        endPage.setLayout(endPageLayout);
        endPageLayout.setHorizontalGroup(
            endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPageLayout.createSequentialGroup()
                .addGroup(endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endPageLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(endLabel))
                    .addGroup(endPageLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(scoreLabel)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        endPageLayout.setVerticalGroup(
            endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endLabel)
                .addGap(43, 43, 43)
                .addComponent(scoreLabel)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        quizPanel.add(endPage, "cardEnd");

        quizSevenTeenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizSevenTeenLabel.setText("Q. How many known surviving kakapo are left in New Zealand?");

        groupForQuiz17.add(answer17A);
        answer17A.setText("Over 9000");

        groupForQuiz17.add(answer17B);
        answer17B.setText("Fewer than 160");

        groupForQuiz17.add(answer17C);
        answer17C.setText("More than 500\n");

        groupForQuiz17.add(answer17D);
        answer17D.setText("Less than 10");

        javax.swing.GroupLayout quiz17Layout = new javax.swing.GroupLayout(quiz17);
        quiz17.setLayout(quiz17Layout);
        quiz17Layout.setHorizontalGroup(
            quiz17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz17Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(quiz17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer17D)
                    .addComponent(answer17C)
                    .addComponent(answer17B)
                    .addComponent(answer17A))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quiz17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quizSevenTeenLabel)
                .addGap(67, 67, 67))
        );
        quiz17Layout.setVerticalGroup(
            quiz17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizSevenTeenLabel)
                .addGap(18, 18, 18)
                .addComponent(answer17A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer17B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer17C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer17D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz17, "card17");

        quizSixteenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizSixteenLabel.setText("Q. Adult male tuataras measure up to");

        groupForQuiz16.add(answer16A);
        answer16A.setText("2 meters");

        groupForQuiz6.add(answer16B);
        answer16B.setText("1 meter");

        groupForQuiz16.add(answer16C);
        answer16C.setText("50 Centimetres");

        groupForQuiz16.add(answer16D);
        answer16D.setText("10 Centimetres");

        javax.swing.GroupLayout quiz16Layout = new javax.swing.GroupLayout(quiz16);
        quiz16.setLayout(quiz16Layout);
        quiz16Layout.setHorizontalGroup(
            quiz16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz16Layout.createSequentialGroup()
                .addGroup(quiz16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quiz16Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(quiz16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer16D)
                            .addComponent(answer16C)
                            .addComponent(answer16B)
                            .addComponent(answer16A)))
                    .addGroup(quiz16Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(quizSixteenLabel)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        quiz16Layout.setVerticalGroup(
            quiz16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizSixteenLabel)
                .addGap(18, 18, 18)
                .addComponent(answer16A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer16B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer16C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer16D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz16, "card16");

        quizFifteenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizFifteenLabel.setText("Q. What time of day are weta most active");

        groupForQuiz15.add(answer15A);
        answer15A.setText("Day");
        answer15A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer15AActionPerformed(evt);
            }
        });

        groupForQuiz15.add(answer15B);
        answer15B.setText("Night");
        answer15B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer15BActionPerformed(evt);
            }
        });

        groupForQuiz15.add(answer15C);
        answer15C.setText("Dusk");

        groupForQuiz15.add(answer15D);
        answer15D.setText("Dawn");

        javax.swing.GroupLayout quiz15Layout = new javax.swing.GroupLayout(quiz15);
        quiz15.setLayout(quiz15Layout);
        quiz15Layout.setHorizontalGroup(
            quiz15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz15Layout.createSequentialGroup()
                .addGroup(quiz15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quiz15Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(quiz15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer15D)
                            .addComponent(answer15C)
                            .addComponent(answer15B)
                            .addComponent(answer15A)))
                    .addGroup(quiz15Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(quizFifteenLabel)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        quiz15Layout.setVerticalGroup(
            quiz15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizFifteenLabel)
                .addGap(18, 18, 18)
                .addComponent(answer15A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer15B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer15C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer15D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz15, "card15");

        quizForteenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizForteenLabel.setText("Q. Why are New Zealand bats rapidly heading towards extinction");

        groupForQuiz14.add(answer14A);
        answer14A.setText("Rat plagues");
        answer14A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer14AActionPerformed(evt);
            }
        });

        groupForQuiz14.add(answer14B);
        answer14B.setText("Predation");
        answer14B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer14BActionPerformed(evt);
            }
        });

        groupForQuiz14.add(answer14C);
        answer14C.setText("Habitat loss");

        groupForQuiz14.add(answer14D);
        answer14D.setText("Global warming\n");

        javax.swing.GroupLayout quiz14Layout = new javax.swing.GroupLayout(quiz14);
        quiz14.setLayout(quiz14Layout);
        quiz14Layout.setHorizontalGroup(
            quiz14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz14Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(quiz14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer14D)
                    .addComponent(answer14A)
                    .addComponent(quizForteenLabel)
                    .addComponent(answer14B)
                    .addComponent(answer14C))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        quiz14Layout.setVerticalGroup(
            quiz14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizForteenLabel)
                .addGap(24, 24, 24)
                .addComponent(answer14A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer14B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer14C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer14D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz14, "card14");

        quizThirteenLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizThirteenLabel1.setText("Q. Why are possums a danger to the native wildlife");

        groupForQuiz13.add(answer13A);
        answer13A.setText("Hunt native wildlife");
        answer13A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer13AActionPerformed(evt);
            }
        });

        groupForQuiz13.add(answer13B);
        answer13B.setText("Compete for food and habitats");
        answer13B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer13BActionPerformed(evt);
            }
        });

        groupForQuiz13.add(answer13C);
        answer13C.setText("Steal native bird eggs");

        groupForQuiz13.add(answer13D);
        answer13D.setText("Attract other predators and pests");

        javax.swing.GroupLayout quiz13Layout = new javax.swing.GroupLayout(quiz13);
        quiz13.setLayout(quiz13Layout);
        quiz13Layout.setHorizontalGroup(
            quiz13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz13Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(quiz13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer13D)
                    .addComponent(answer13A)
                    .addComponent(quizThirteenLabel1)
                    .addComponent(answer13B)
                    .addComponent(answer13C))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        quiz13Layout.setVerticalGroup(
            quiz13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizThirteenLabel1)
                .addGap(18, 18, 18)
                .addComponent(answer13A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer13B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer13C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer13D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz13, "card13");

        quizTwelveLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizTwelveLabel2.setText("Q. Stoats are a danger to the native wildlife because");

        groupForQuiz12.add(answer12A);
        answer12A.setText("They are predators of native birds");
        answer12A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer12AActionPerformed(evt);
            }
        });

        groupForQuiz12.add(answer12B);
        answer12B.setText("They steal and eat the limited supply of food");
        answer12B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer12BActionPerformed(evt);
            }
        });

        groupForQuiz12.add(answer12C);
        answer12C.setText("They destory natural habitats\n");

        groupForQuiz12.add(answer12D);
        answer12D.setText("They spread diseases to native wildlife");

        javax.swing.GroupLayout quiz12Layout = new javax.swing.GroupLayout(quiz12);
        quiz12.setLayout(quiz12Layout);
        quiz12Layout.setHorizontalGroup(
            quiz12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz12Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(quiz12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer12D)
                    .addComponent(answer12A)
                    .addComponent(quizTwelveLabel2)
                    .addComponent(answer12B)
                    .addComponent(answer12C))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        quiz12Layout.setVerticalGroup(
            quiz12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizTwelveLabel2)
                .addGap(18, 18, 18)
                .addComponent(answer12A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer12B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer12C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer12D)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        quizPanel.add(quiz12, "card12");

        getContentPane().add(quizPanel, java.awt.BorderLayout.CENTER);

        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addComponent(buttonNext)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(buttonNext)
                .addContainerGap())
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        buttonNext.setEnabled(false);
        Collections.shuffle(game.getFacts());
        
        
        //CardLayout card = (CardLayout) quizPanel.getLayout();
        //card.next(quizPanel);
        if (iterator < 5) {
            // show card
            if (game.getFacts().get(iterator).equals("There are about 68,000 kiwi left in all of New Zealand.")) {
                //card.show(quizPanel, "card1");
                if (answer1C.isSelected()){
                    //JOptionPane.showMessageDialog(this, endPage, title, HEIGHT, icon);
                }
                // game.addPointS(3)
                // show dialog "Correct"
                 buttonNext.setEnabled(true);
                 card.show(quizPanel, "card1");
            } else if (game.getFacts().get(iterator).equals("We are losing 2% of our unmanaged kiwi every year –that's around 20 per week.")) {
                card.show(quizPanel, "card2");
            } else if (game.getFacts().get(iterator).equals("Kiwi are mostly nocturnal.")) {
                card.show(quizPanel, "card3");
            } else if (game.getFacts().get(iterator).equals("Kiwi nest in burrows, hollow logs or under dense vegetation.")) {
                card.show(quizPanel, "card4");
            } else if (game.getFacts().get(iterator).equals("Kiwi are the only bird to have nostrils at the end of their very long bill. Their nostrils are used to probe in the ground, sniffing out invertebrates to eat, along with some fallen fruit.")) {
                card.show(quizPanel, "card5");
            } else if (game.getFacts().get(iterator).equals("The egg averages 15% of the female's body weight (compared to 2% for the ostrich).")) {
                card.show(quizPanel, "card6");
            } else if (game.getFacts().get(iterator).equals("Females are larger than males (up to 3.3 kg and 45 cm).")) {
                card.show(quizPanel, "card7");
            } else if (game.getFacts().get(iterator).equals("Kiwi are long-lived, and depending on the species live for between 25 and 50 years.")) {
                card.show(quizPanel, "card8");
            } else if (game.getFacts().get(iterator).equals("Rat")) {
                card.show(quizPanel, "card9");
            } else if (game.getFacts().get(iterator).equals("Cat")) {
                card.show(quizPanel, "card10");
            } else if (game.getFacts().get(iterator).equals("Kiore")) {
                card.show(quizPanel, "card11");
            } else if (game.getFacts().get(iterator).equals("Stoat")) {
                card.show(quizPanel, "card12");
            } else if (game.getFacts().get(iterator).equals("Possum")) {
                card.show(quizPanel, "card13");
            } else if (game.getFacts().get(iterator).equals("Bat")) {
                card.show(quizPanel, "card14");
            } else if (game.getFacts().get(iterator).equals("Weta")) {
                card.show(quizPanel, "card15");
            } else if (game.getFacts().get(iterator).equals("Tuatara")) {
                card.show(quizPanel, "card16");
            } else if (game.getFacts().get(iterator).equals("Kakapu")) {
                card.show(quizPanel, "card17");
            }
            //}
            //else if{
            //
            //}
            //card.show(quizPanel, "card"+iterator);
            iterator++;
        }else if(iterator < 5){
            
        }
        else{
            // show endCard
            card.show(quizPanel, "cardEnd");
            //scoreLabel.setText("Your score is "+game.getScore());
            // set text to show score
            // game.ifhighScore(game.getScore);
            // popup to Save score?
            // game.addHighScore(game.getScore, jTextField.getText().toString);
            
        }
        
    }//GEN-LAST:event_buttonNextActionPerformed

    private void answer2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2AActionPerformed

    private void answer15AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer15AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer15AActionPerformed

    private void answer15BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer15BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer15BActionPerformed

    private void answer14AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer14AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer14AActionPerformed

    private void answer14BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer14BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer14BActionPerformed

    private void answer13AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer13AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer13AActionPerformed

    private void answer13BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer13BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer13BActionPerformed

    private void answer12AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer12AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer12AActionPerformed

    private void answer12BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer12BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer12BActionPerformed

    public void createQuiz(){
        //Collections.shuffle(game.getFacts());
        /*
        for(int i = 0; i < 5; i++){
            if(i == 0){
                if(facts.get(i).equals("There are about 68,000 kiwi left in all of New Zealand.")){
                    /
                }else if(facts.get(i).equals("We are losing 2% of our unmanaged kiwi every year –that's around 20 per week.")){
                    
                }else if(facts.get(i).equals("Kiwi are mostly nocturnal.")){
                    
                }else if(facts.get(i).equals("Kiwi nest in burrows, hollow logs or under dense vegetation.")){
                    
                }else if(facts.get(i).equals("Kiwi are the only bird to have nostrils at the end of their very long bill. Their nostrils are used to probe in the ground, sniffing out invertebrates to eat, along with some fallen fruit.")){
                    
                }else if(facts.get(i).equals("The egg averages 15% of the female's body weight (compared to 2% for the ostrich).")){
                    
                }else if(facts.get(i).equals("Females are larger than males (up to 3.3 kg and 45 cm).")){
                    
                }else if(facts.get(i).equals("Kiwi are long-lived, and depending on the species live for between 25 and 50 years.")){
                    
                }else if(facts.get(i).equals("Rat")){
                    
                }else if(facts.get(i).equals("Cat")){
                    
                }else if(facts.get(i).equals("Kiore")){
                    
                }else if(facts.get(i).equals("Stoat")){
                    
                }else if(facts.get(i).equals("Possum")){
                    
                }else if(facts.get(i).equals("Bat")){
                    
                }else if(facts.get(i).equals("Weta")){
                    
                }else if(facts.get(i).equals("Tuatara")){
                    
                }else if(facts.get(i).equals("Kakapu")){
                    
                }
            }else if(i == 1){
                
            }else if(i == 2){
                
            }else if(i == 3){
                
            }else{
                
            }
            
        }
        */
    }
    
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BonusQuizUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BonusQuizUI2().setVisible(true);
//            }
//        });
//    }
    private int iterator = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answer12A;
    private javax.swing.JRadioButton answer12B;
    private javax.swing.JRadioButton answer12C;
    private javax.swing.JRadioButton answer12D;
    private javax.swing.JRadioButton answer13A;
    private javax.swing.JRadioButton answer13B;
    private javax.swing.JRadioButton answer13C;
    private javax.swing.JRadioButton answer13D;
    private javax.swing.JRadioButton answer14A;
    private javax.swing.JRadioButton answer14B;
    private javax.swing.JRadioButton answer14C;
    private javax.swing.JRadioButton answer14D;
    private javax.swing.JRadioButton answer15A;
    private javax.swing.JRadioButton answer15B;
    private javax.swing.JRadioButton answer15C;
    private javax.swing.JRadioButton answer15D;
    private javax.swing.JRadioButton answer16A;
    private javax.swing.JRadioButton answer16B;
    private javax.swing.JRadioButton answer16C;
    private javax.swing.JRadioButton answer16D;
    private javax.swing.JRadioButton answer17A;
    private javax.swing.JRadioButton answer17B;
    private javax.swing.JRadioButton answer17C;
    private javax.swing.JRadioButton answer17D;
    private javax.swing.JRadioButton answer1A;
    private javax.swing.JRadioButton answer1B;
    private javax.swing.JRadioButton answer1C;
    private javax.swing.JRadioButton answer1D;
    private javax.swing.JRadioButton answer2A;
    private javax.swing.JRadioButton answer2B;
    private javax.swing.JRadioButton answer2C;
    private javax.swing.JRadioButton answer2D;
    private javax.swing.JRadioButton answer3A;
    private javax.swing.JRadioButton answer3B;
    private javax.swing.JRadioButton answer3C;
    private javax.swing.JRadioButton answer3D;
    private javax.swing.JRadioButton answer4A;
    private javax.swing.JRadioButton answer4B;
    private javax.swing.JRadioButton answer4C;
    private javax.swing.JRadioButton answer4D;
    private javax.swing.JRadioButton answer5A;
    private javax.swing.JRadioButton answer5B;
    private javax.swing.JRadioButton answer5C;
    private javax.swing.JRadioButton answer5D;
    private javax.swing.JRadioButton answer6A;
    private javax.swing.JRadioButton answer6B;
    private javax.swing.JRadioButton answer6C;
    private javax.swing.JRadioButton answer6D;
    private javax.swing.JButton buttonNext;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel endPage;
    private javax.swing.ButtonGroup groupForQuiz1;
    private javax.swing.ButtonGroup groupForQuiz12;
    private javax.swing.ButtonGroup groupForQuiz13;
    private javax.swing.ButtonGroup groupForQuiz14;
    private javax.swing.ButtonGroup groupForQuiz15;
    private javax.swing.ButtonGroup groupForQuiz16;
    private javax.swing.ButtonGroup groupForQuiz17;
    private javax.swing.ButtonGroup groupForQuiz2;
    private javax.swing.ButtonGroup groupForQuiz3;
    private javax.swing.ButtonGroup groupForQuiz4;
    private javax.swing.ButtonGroup groupForQuiz5;
    private javax.swing.ButtonGroup groupForQuiz6;
    private javax.swing.ButtonGroup groupForQuiz7;
    private javax.swing.ButtonGroup groupForQuiz8;
    private javax.swing.ButtonGroup groupForQuiz9;
    private javax.swing.JPanel quiz1;
    private javax.swing.JPanel quiz12;
    private javax.swing.JPanel quiz13;
    private javax.swing.JPanel quiz14;
    private javax.swing.JPanel quiz15;
    private javax.swing.JPanel quiz16;
    private javax.swing.JPanel quiz17;
    private javax.swing.JPanel quiz2;
    private javax.swing.JPanel quiz3;
    private javax.swing.JPanel quiz4;
    private javax.swing.JPanel quiz5;
    private javax.swing.JPanel quiz6;
    private javax.swing.JLabel quizFifteenLabel;
    private javax.swing.JLabel quizFiveLabel;
    private javax.swing.JLabel quizForteenLabel;
    private javax.swing.JLabel quizFourLabel;
    private javax.swing.JLabel quizOneLabel;
    private javax.swing.JPanel quizPanel;
    private javax.swing.JLabel quizSevenTeenLabel;
    private javax.swing.JLabel quizSixLabel;
    private javax.swing.JLabel quizSixteenLabel;
    private javax.swing.JLabel quizThirteenLabel1;
    private javax.swing.JLabel quizThreeLabel;
    private javax.swing.JLabel quizTwelveLabel2;
    private javax.swing.JLabel quizTwoLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel startPage;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
